version: '3.9'

services:
  # ================================
  # GeoSat Gateway Application
  # ================================
  geosat-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: geosat-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JAVA_OPTS=-Xmx512m -Xms256m
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - geosat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 40s

  # ================================
  # Redis Cache
  # ================================
  redis:
    image: redis:7-alpine
    container_name: geosat-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - redis-data:/data
    networks:
      - geosat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # ================================
  # Prometheus (Monitoring)
  # ================================
  prometheus:
    image: prom/prometheus:latest
    container_name: geosat-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - geosat-network
    restart: unless-stopped
    depends_on:
      - geosat-gateway

  # ================================
  # Grafana (Dashboards)
  # ================================
  grafana:
    image: grafana/grafana:latest
    container_name: geosat-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=geosat123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./observability/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./observability/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
      - grafana-data:/var/lib/grafana
    networks:
      - geosat-network
    restart: unless-stopped
    depends_on:
      - prometheus

# ================================
# Networks
# ================================
networks:
  geosat-network:
    driver: bridge
    name: geosat-network

# ================================
# Volumes
# ================================
volumes:
  redis-data:
    name: geosat-redis-data
  prometheus-data:
    name: geosat-prometheus-data
  grafana-data:
    name: geosat-grafana-data
