server:
  port: 8080
spring:
  application:
    name: geosat-gateway
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: geosat-gateway
      environment: ${SPRING_PROFILES_ACTIVE:development}
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    prometheus:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{correlationId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.geosat.gateway: DEBUG

resilience4j:
  retry:
    instances:
      rbmcClient:
        max-attempts: 4
        wait-duration: 500ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
  circuitbreaker:
    instances:
      rbmcClient:
        slidingWindowSize: 20
        failureRateThreshold: 50
        waitDurationInOpenState: 30s

rbmc:
  circuitBreaker:
    waitOpenSeconds: 30

---
# Perfil Docker
spring:
  config:
    activate:
      on-profile: docker

logging:
  level:
    root: INFO
    com.geosat.gateway: DEBUG
