spring:
  data:
    redis:
      host: 127.0.0.1
      port: 65535 # porta inválida para garantir que ninguém conecte

resilience4j:
  retry:
    instances:
      rbmcClient:
        wait-duration: 10ms
        max-attempts: 4
        enable-exponential-backoff: false
  circuitbreaker:
    instances:
      rbmcClient:
        slidingWindowSize: 4
        minimumNumberOfCalls: 4
        failureRateThreshold: 50
        waitDurationInOpenState: 1s

logging:
  level:
    com.geosat.gateway: WARN